name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install python requirements 
      run: pip3 install -r requirements.txt 
    - name: collect-dependencies
      run: git submodule update --recursive --init 
    - name: get clang 
      run: apt install clang 
    - name: build cpp
      run: mkdir build && cd build && cmake ../ && make -j4 -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang && make test
    - name: test python
      run: cd python && pytest ./test
