name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: fetch llvm key
      run:  wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add
    - name: add apt repo
      run: sudo add-apt-repository 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main' 
    - name: install clang 
      run: sudo apt install libllvm-11-ocaml-dev libllvm11 llvm-11 llvm-11-dev llvm-11-doc llvm-11-examples llvm-11-runtime clang-11 clang-tools-11 clang-11-doc libclang-common-11-dev libclang-11-dev libclang1-11
    - name: Install python requirements 
      run: pip3 install -r requirements.txt 
    - name: collect-dependencies
      run: git submodule update --recursive --init 
    - name: build cpp
      run: mkdir build && cd build && cmake ../ -DCMAKE_CXX_COMPILER=clang++-11 -DCMAKE_C_COMPILER=clang-11 -DBUILD_SHARED_LIBS=1 -DCMAKE_BUILD_TYPE=Debug && make -j4 && make test
    - name: test python
      run: cd python && pytest ./test
